language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script:
        - yarn run lint
        - yarn run flow
        - yarn run test
    - stage: build
      script:
        - yarn run build
branches:
  only:
  - master
