export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_ACTIVE_MONTH = 'SET_ACTIVE_MONTH';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const GET_PERSONS_REQUEST = 'GET_PERSONS_REQUEST';
export const GET_PERSONS_SUCCESS = 'GET_PERSONS_SUCCESS';
export const GET_PERSONS_FAILURE = 'GET_PERSONS_FAILURE';
